=== CGMarval/LND/PracticasDossier_T5/libreria.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libreria (libro+)>
<!ELEMENT libro (titulo, autor,editorial)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>

=== CGMarval/LND/PracticasDossier_T5/Practica5/Practica5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE libreria SYSTEM "/home/esteban/LND/libreria.dtd">
<libreria>
        <libro>
              <titulo> H치bitos At칩micos</titulo>
              <autor> James Clear</autor>
              <autor> Cameron Lear</autor>
              <editorial> Diana</editorial>
        </libro>
        <libro>
              <titulo> El monje que vendi칩 su ferrari</titulo>
              <autor> Robin Sharma</autor>
              <editorial> Clave</editorial>
        </libro>
       <libro>
              <titulo> Los 7 H치bitos de la gente altamente efectiva</titulo>
              <autor> Stephen Covey</autor>
              <editorial> Booket</editorial>
        </libro>        
</libreria>
