=== CGMarval/LND/enunciadosXML-DTD/Ejercicio1/clase.dtd
<!ELEMENT clases (clase)+>
<!ELEMENT clase (profesor+,(alumno|alumna )+)>
<!ELEMENT profesor (nombre, apellidos*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT alumno (nombre,apellidos)>
<!ELEMENT alumna (nombre,apellidos)>

=== CGMarval/LND/enunciadosXML-DTD/Ejercicio1/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Tue Oct 10 16:13:26 WEST 2023 -->


<!DOCTYPE clase SYSTEM "clase.dtd">

<clase>
	<profesor>
		<nombre>
		</nombre>
		
		<apellidos>
		</apellidos>
	
	</profesor>
	
	<alumno>
		<nombre>
		</nombre>
		<apellidos>
		</apellidos>
	</alumno>
	
	<alumna>
		<nombre>
		</nombre>
		<apellidos>
		</apellidos>
	</alumna>
	
</clase>
